alias ga='git add'
alias gb='git branch -vv'
alias gca='git commit --amend'
alias gcm='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --staged'
alias gfh='git flathist'
alias ghi='git hist'
alias gl='git log'
alias gff='git merge --ff-only @{u}'
alias gp='git push'
alias gru='git remote update'
alias gruff='gru && gff'
alias gsh='git show'
alias gst='git status'
alias vim='nvim'
alias zr='exec zsh'
alias grep='grep --color=auto'
alias ls='ls --color=auto'
